### ISSUE TITLE
Deprecated ColorType error message

### ISSUE THREAD

**Issue by ossinkine** [sonata-project/SonataCoreBundle#580]
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle    3.40.3 = 3.40.3 The missing Symfony Admin Generator
sonata-project/block-bundle    3.12.1 = 3.12.1 Symfony SonataBlockBundle
sonata-project/cache           1.0.7  = 1.0.7  Cache library
sonata-project/core-bundle     3.11.2 = 3.11.2 Symfony SonataCoreBundle
sonata-project/datagrid-bundle 2.4.0  = 2.4.0  Symfony SonataDatagridBundle
sonata-project/exporter        1.9.1  = 1.9.1  Lightweight Exporter library
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
symfony/monolog-bundle     v3.3.0  ! v3.3.1  Symfony MonologBundle
symfony/phpunit-bridge     v3.4.18 ~ v4.1.7  Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.10.0 = v1.10.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-ctype     v1.10.0 = v1.10.0 Symfony polyfill for ctype functions
symfony/polyfill-intl-icu  v1.10.0 = v1.10.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.10.0 = v1.10.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.10.0 = v1.10.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.10.0 = v1.10.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.10.0 = v1.10.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.1  = v3.0.1  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.7  ~ v3.0.3  Symfony SwiftmailerBundle
symfony/symfony            v3.4.18 = v3.4.18 The Symfony PHP framework
```

#### PHP version

```
$ php -v
PHP 7.2.8 (cli) (built: Jul 21 2018 08:05:40) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
```

## Subject

I've setup a new Symfony 3.4 project with Sonata Admin and got an error `The Sonata\CoreBundle\Form\Type\ColorType class is deprecated since version 3.10 and will be removed in 4.0. Use Symfony\Component\Form\Extension\Core\Type\ColorType instead.` on container compiling.

## Steps to reproduce

```
composer create-project symfony/framework-standard-edition foo
cd foo
composer require sonata-project/admin-bundle
# configure admin bundle according to https://github.com/sonata-project/SonataAdminBundle/blob/3.x/docs/getting_started/installation.rst
composer require phpunit/phpunit --dev
./vendor/bin/phpunit
```

## Expected results

```
  1x: The Sonata\CoreBundle\Form\Type\ColorType class is deprecated since version 3.10 and will be removed in 4.0. Use Symfony\Component\Form\Extension\Core\Type\ColorType instead.
    1x in DefaultControllerTest::testIndex from Tests\AppBundle\Controller
```

## Actual results

No deprecation messages

**Comment by kunicmarko20** [comment]
https://github.com/sonata-project/SonataCoreBundle/blob/65e002828f83f604970aa87f247340a80ce9dc95/src/Form/Type/ColorType.php#L18

Well, it is deprecated and shouldn't be used, this is expected behavior?

**Comment by ossinkine** [comment]
@kunicmarko20  I'm not using it, I have an empty just installed project

**Comment by tifabien** [comment]
@kunicmarko20 I was also thinking about this issue. I think the main issue here is that even if we are not using this FormType, the error is triggered (Maybe a compiler pass is loading it?). It force us for instance to increase the SYMFONY_DEPRECATIONS_HELPER's value in the phpunit.xml file if we want our unit tests to pass. Maybe we could move this trigger_error call inside the FormType, this way the error will be triggered only if it's really used?

What do you think?

**Comment by greg0ire** [comment]
We should try to understand the bug first… please run `SYMFONY_DEPRECATIONS_HELPER=/ColorType/ phpunit` to get a stack trace

**Comment by core23** [comment]
Same problem like https://github.com/sonata-project/SonataCoreBundle/pull/647 @greg0ire ?

**Comment by tifabien** [comment]
@greg0ire I'll execute the command tomorrow. I'll let you know the result.

**Comment by tifabien** [comment]
@greg0ire here is the stack trace : 
```
PHPUnit 6.5.13 by Sebastian Bergmann and contributors.

Remaining deprecation triggered by Tests\AppBundle\Command\ContentImporterCommandTest::setUp:
The Sonata\CoreBundle\Form\Type\ColorType class is deprecated since version 3.10 and will be removed in 4.0. Use Symfony\Component\Form\Extension\Core\Type\ColorType instead.
Stack trace:
#0 vendor/sonata-project/core-bundle/src/CoreBundle/Form/Type/ColorType.php(21): trigger_error('The Sonata\\Core...', 16384)
#1 vendor/composer/ClassLoader.php(444): include('/home/fab/Docum...')
#2 vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/home/fab/Docum...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Sonata\\CoreBund...')
#4 [internal function]: spl_autoload_call('Sonata\\CoreBund...')
#5 vendor/symfony/symfony/src/Symfony/Component/Config/Resource/ClassExistenceResource.php(78): class_exists('Sonata\\CoreBund...')
#6 vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php(371): Symfony\Component\Config\Resource\ClassExistenceResource->isFresh(0)
#7 vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php(363): Symfony\Component\DependencyInjection\ContainerBuilder->getReflectionClass('Sonata\\CoreBund...', false)
#8 vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php(336): Symfony\Component\DependencyInjection\Compiler\AutowirePass->populateAvailableType('sonata.core.for...', Object(Symfony\Component\DependencyInjection\Definition), false)
#9 vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php(292): Symfony\Component\DependencyInjection\Compiler\AutowirePass->populateAvailableTypes(false)
#10 vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php(125): Symfony\Component\DependencyInjection\Compiler\AutowirePass->getAutowiredReference(Object(Symfony\Component\DependencyInjection\TypedReference), 'for "Symfony\\Co...')
#11 vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php(109): Symfony\Component\DependencyInjection\Compiler\AutowirePass->doProcessValue(Object(Symfony\Component\DependencyInjection\TypedReference), false)
#12 vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(60): Symfony\Component\DependencyInjection\Compiler\AutowirePass->processValue(Object(Symfony\Component\DependencyInjection\TypedReference), false)
#13 vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php(130): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, false)
#14 vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php(109): Symfony\Component\DependencyInjection\Compiler\AutowirePass->doProcessValue(Array, false)
#15 vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(65): Symfony\Component\DependencyInjection\Compiler\AutowirePass->processValue(Array)
#16 vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php(130): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Object(Symfony\Component\DependencyInjection\Argument\ServiceClosureArgument), false)
#17 vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php(109): Symfony\Component\DependencyInjection\Compiler\AutowirePass->doProcessValue(Object(Symfony\Component\DependencyInjection\Argument\ServiceClosureArgument), false)
#18 vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(60): Symfony\Component\DependencyInjection\Compiler\AutowirePass->processValue(Object(Symfony\Component\DependencyInjection\Argument\ServiceClosureArgument), false)
#19 vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php(130): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, false)
#20 vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php(109): Symfony\Component\DependencyInjection\Compiler\AutowirePass->doProcessValue(Array, false)
#21 vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(60): Symfony\Component\DependencyInjection\Compiler\AutowirePass->processValue(Array, false)
#22 vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php(130): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, false)
#23 vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php(109): Symfony\Component\DependencyInjection\Compiler\AutowirePass->doProcessValue(Array, false)
#24 vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(67): Symfony\Component\DependencyInjection\Compiler\AutowirePass->processValue(Array)
#25 vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php(130): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Object(Symfony\Component\DependencyInjection\Definition), true)
#26 vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php(109): Symfony\Component\DependencyInjection\Compiler\AutowirePass->doProcessValue(Object(Symfony\Component\DependencyInjection\Definition), true)
#27 vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(60): Symfony\Component\DependencyInjection\Compiler\AutowirePass->processValue(Object(Symfony\Component\DependencyInjection\Definition), true)
#28 vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php(130): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, true)
#29 vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php(109): Symfony\Component\DependencyInjection\Compiler\AutowirePass->doProcessValue(Array, true)
#30 vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php(39): Symfony\Component\DependencyInjection\Compiler\AutowirePass->processValue(Array, true)
#31 vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php(70): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#32 vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php(141): Symfony\Component\DependencyInjection\Compiler\AutowirePass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#33 vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php(790): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#34 vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(637): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#35 vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#36 Tests/AppBundle/Command/ContentImporterCommandTest.php(402): Symfony\Component\HttpKernel\Kernel->boot()
#37 vendor/phpunit/phpunit/src/Framework/TestCase.php(935): Tests\AppBundle\Command\ContentImporterCommandTest->setUp()
#38 {main}
```

**Comment by greg0ire** [comment]
> Maybe a compiler pass is loading it?

Looks like you were right!

**Comment by tifabien** [comment]
Yeah ! Now how to handle correctly all these deprecations? Maybe move the `trigger_error` in the `getName` method?

**Comment by greg0ire** [comment]
Symfony has deprecated `getName`… maybe add a `buildForm` method just for this? That way we will be a bit more sure the form is actually used.
